### ISSUE TITLE
Unity 2020.3.11f1 LTS - GRADLE ERROR

### ISSUE THREAD

**Issue by Eelam** [Aryzon/unity-sdk#1]
I am trying to test the new SDK using **Unity 2020.3.11** and I am getting the following build errors (GRADLE)
•	GRADLE ERROR : resource-not-found UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
•	Configure project :launcher
•	FAILURE: Build failed with an exception.
•	CommandInvokationFailure: Gradle build failed.
•	Build completed with a result of 'Failed' in 19 seconds (19291 ms) UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
•	UnityEditor.BuildPlayerWindow+BuildMethodException: 4 errors at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002ca] in <0b8db76a688c4d18a15dd7dfe092a035>:0  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in <0b8db76a688c4d18a15dd7dfe092a035>:0 
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by maartenslaa** [comment]
Thank your for bringing this to our attention. The official Google Cardboard SDK has updated their setup settings. You should now not do any of what [they say here](https://developers.google.com/cardboard/develop/unity/quickstart#publishing_settings).

Instead just add these lines as dependencies to a newly created main gradle template:

```
implementation 'com.android.support:appcompat-v7:28.0.0'
implementation 'com.android.support:support-v4:28.0.0'
implementation 'com.google.android.gms:play-services-vision:15.0.2'
implementation 'com.google.protobuf:protobuf-javalite:3.8.0'
```

**Comment by maartenslaa** [comment]
I have updated the [README.md](https://github.com/Aryzon/unity-sdk/commit/0a11652325510550007fa22aba77fdec038f622e) accordingly. I hope this will help you out. Can you let me know if the error has gone away with these settings?
